### ISSUE TITLE
What process is the target here and how is it created

### ISSUE THREAD

**Issue by rootkiter** [smx-smx/ezinject#16]
What process is the target here and how is it created

https://github.com/smx-smx/ezinject/blob/a88709d32d3474697c855a563dd6069b6dc95599/README.md?plain=1#L157

**Comment by smx-smx** [comment]
`target` is the sample program built as part of `./samples/dummy`.
It's a simple and dummy program that loops endlessly, printing numbers and sleeping.
In normal uses, you would target (hence the name) the process you want to inject into, replacing `pidof target` with your Process ID.
For testing purposes, we created a dummy program that acts as our test target and is used by Continuous Integration to test ezinject.
