### ISSUE TITLE
Documentation with hands-on examples?

### ISSUE THREAD

**Issue by tuxuser** [smx-smx/ezinject#3]
Hello

I just started learning about dll injections and hooking yesterday and your tool sounds very promising.

The README is pretty expressive when it comes to technical details and Example code is provided in `samples` directory

BUT

Is there any hands-on example with explanation, how one utilizes the lib from start to finish? Like a 'Quick start guide' ?

**Comment by jonatron** [comment]
Install dependencies (debian/ubuntu)
`sudo apt install build-essential cmake libcapstone-dev pkg-config`

Compile:
`./build.sh`

If build errors, fix and use:
`./build.sh clean`

Terminal 1:
`$ cd build/samples/dummy`
`$ ./target`

Terminal 2:
`$ cd build`
``$ sudo ./ezinject `pidof target` samples/dummy/libdummy.so``

Hopefully see:

`return1() = 1`
change to
`return1() = 13370`


Try playing with `samples/dummy/libdummy.c`

To use python:

`echo "print('hello ' * 3 + 'from python');" > hello.py`

``export EZPY=`python -c "import sys; print(':'.join(sys.path))"` ``
`echo "python path: $EZPY"`

Find libpython:
`find /usr/lib -name "libpython*"`
Put correct libpython and paths in example below:
``sudo ./ezinject `pidof target` samples/pyloader/libpyloader.so /usr/lib/x86_64-linux-gnu/libpython2.7.so.1 /usr/lib/python2.7 $EZPY hello.py``

**Comment by tuxuser** [comment]
@jonatron Thaks alot for the detailed explaination.

Can I possibly wrap this up and send a PR to the README? Or would you rather like to do it?
It should benefit also others, if such instructions are directly visible when looking at the repo.

**Comment by smx-smx** [comment]
If you want to, you're more than welcome

I've been busy porting ezinject to android and freebsd 😉

**Comment by tuxuser** [comment]
Built a PR (#4) with that intel :)
